### ISSUE TITLE
ValidationError: 2 validation errors for HumanMessage at v1.0.0a59

### ISSUE THREAD

**Issue by songjinu** [langflow-ai/langflow#2195] opened 2024-06-17 07:34 UTC
**Describe the bug**
ValidationError: 2 validation errors for HumanMessage at v1.0.0a59
I connect ChatInput - OpenAI without Prompt.
```
ValidationError: 2 validation errors for HumanMessage
                             content
                               str type expected (type=type_error.str)
                             content
                               value is not a valid list (type=type_error.list)
```
```
\src\backend\base\langflow\base\models\model.py:104 in get_chat_result                                       │ 
                             │                                                                                                                               │ 
                             │   101 │   │   │   │   │   else:                                                                                               │ 
                             │   102 │   │   │   │   │   │   messages.append(input_value.to_lc_message())                                                    │ 
                             │   103 │   │   │   else:                                                                                                       │ 
                             │ ❱ 104 │   │   │   │   messages.append(HumanMessage(content=input_value))                                                      │ 
                             │   105 │   │   inputs = messages or {}                                                                                         │ 
                             │   106 │   │   if stream:                                                                                                      │ 
                             │   107 │   │   │   return runnable.stream(inputs)                                          
```
**Browser and Version**
 - Version [v1.0.0a59]

**Screenshots**

**Comment by msmygit** [comment] 2024-06-17 15:14
Already reported earlier at #2182 for a58 and continues to be an issue with a59 version as well.

**Comment by nicoloboschi** [comment] 2024-06-28 10:28
Is the problem still there with langflow 1.0.5?

**Comment by nicoloboschi** [comment] 2024-06-28 14:54
Duplicate of #2182

**Closed by nicoloboschi** 2024-06-28 14:54 UTC
Labels: bug
