### ISSUE TITLE
v1.0 AttributeError: build_model not found in AzureChatOpenAIComponent

### ISSUE THREAD

**Issue by 714Lemons** [langflow-ai/langflow#2331] opened 2024-06-25 07:54 UTC
**Describe the bug**
The Azure OpenAI component does not work and returns AttributeError. build_model not found.
I tried every model from gpt-35 up tp gpt-4o.

**Browser and Version**
 - Chrome Version 125.0.6422.176
 - Version 1.0.0 to 10.2,  i wanted to test it also with 1.0.3 but this is currently not working

**To Reproduce**
1. Create Hello World Prompt
2. Replace OpenAI by Azure OpenAI
3. Insert Credentials
4. Run flow
5. See error

**Screenshots**
![Bildschirmfoto 2024-06-25 um 09 52 45](https://github.com/langflow-ai/langflow/assets/32739574/1b597a25-5432-4a36-aeb5-50d2984a54d3)

**Comment by nicoloboschi** [comment] 2024-06-28 10:16
Duplicate of #2333 
will be fixed by https://github.com/langflow-ai/langflow/pull/2339

**Closed by nicoloboschi** 2024-06-28 10:16 UTC
Labels: bug
