### ISSUE TITLE
 ERROR    - setup - Edge between Component and CrewAIAgentComponent has invalid handles       # setup.py:580

### ISSUE THREAD

**Issue by tdhd3** [langflow-ai/langflow#3356] opened 2024-08-15 03:37 UTC
Updated to 1.015 ver. when I open the project, pop up a notion tells me to report to GitHub.
Btw I couldn't access to my project.

Here's the notion:

Sorry, we found an unexpected error!

Please report errors with detailed tracebacks on the [GitHub Issues](https://github.com/langflow-ai/langflow/issues) page.
Thank you!

**Comment by HanumanTFM** [comment] 2024-08-15 23:17
same issue here

**Comment by Cristhianzl** [comment] 2024-08-19 19:26
Hey @HanumanTFM @tdhd3,

I hope you’re all doing well.

I went through every single component trying to get this error, but I couldn’t reproduce it. :(

Could you please provide the exported .JSON file of the flow where you’re encountering the error?
I’ll be waiting for your response so I can proceed with the fix.

Thank you!

**Comment by McCalebTheSecond** [comment] 2024-08-20 20:24
Same error for me.  1.0.15 on windows 11.

**Comment by Cristhianzl** [comment] 2024-08-21 17:35
Hi @McCalebTheSecond, could you please share the flow that's causing the crash? That would help us move forward with the analysis.

Thank you!

**Comment by McCalebTheSecond** [comment] 2024-08-21 17:48
It happens when I start Langflow.

![2024-08-21 12_47_05-setup py - langflowvenv (Workspace) - Visual Studio Code](https://github.com/user-attachments/assets/5934c13a-767a-4fd9-a98c-39f47961eb5f)

**Comment by McCalebTheSecond** [comment] 2024-08-21 17:49
> Hi @McCalebTheSecond, could you please share the flow that's causing the crash? That would help us move forward with the analysis.
> 
> Thank you!

Hey @Cristhianzl, it happens when I start Langflow.

![2024-08-21 12_47_05-setup py - langflowvenv (Workspace) - Visual Studio Code](https://github.com/user-attachments/assets/5934c13a-767a-4fd9-a98c-39f47961eb5f)

**Comment by Geoff3068** [comment] 2024-08-21 18:42
I have the same problem with various fresh installs on Windows 11 using conda environments running various Pythons from 3.10-3.12.
It might be something to do with the SearchAPI component tool connection and the CrewAIAgent component?

**Comment by Cristhianzl** [comment] 2024-08-21 19:10
Hey @Geoff3068, @McCalebTheSecond, @HanumanTFM, @tdhd3,

I wanted to bring #3357 to your attention.

I’ve tested all the basic examples with CrewAI agents on the latest main branch, and everything worked smoothly. It looks like these issues will likely be resolved in the upcoming v1.0.16 release. I recommend waiting for the new release, as these errors shouldn’t cause any major roadblocks.

Thanks for your patience!

**Comment by tdhd3** [comment] 2024-08-22 03:22
In my case, using this Google Search Tool was just fine in v1.0.14. When I
updated to v1.0.15, it doesn;t work any more.

Btw, the terminal server pops out many errors when I first get into the
project work space. So I disconnected the connection.

[image: image.png]

Cristhian Zanforlin Lousa ***@***.***> 於 2024年8月22日 週四
上午3:11寫道：

**Comment by tdhd3** [comment] 2024-08-22 03:24
After the update to v1.0.15. This error shows.

 [image: image.png]

施力珩 ***@***.***> 於 2024年8月22日 週四 上午11:22寫道：

**Closed** 2024-08-23 12:39 UTC
Labels: bug
