### ISSUE TITLE
Error building "SQL Executor" component 

### ISSUE THREAD

**Issue by SavvySupport** [langflow-ai/langflow#4127] opened 2024-10-14 05:03 UTC
### Bug Description

We were using V1.0.16. The SQL Executor component was working fine. 

We upgraded to version V1.0.19. Since then, we've had issues with the "SQL Executor" component. 

When we click on the "play" button on the SQL Executor component, it says:
> 'SQLExecutorComponent' object has no attribute 'set_event_manager'

The component output shows the following:
Traceback (most recent call last):
  File "/langflow/venv/lib/python3.10/site-packages/langflow/api/v1/chat.py", line 219, in _build_vertex
    vertex_build_result = await graph.build_vertex(
  File "/langflow/venv/lib/python3.10/site-packages/langflow/graph/graph/base.py", line 1384, in build_vertex
    await vertex.build(
  File "/langflow/venv/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 832, in build
    await step(user_id=user_id, event_manager=event_manager, **kwargs)
  File "/langflow/venv/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 498, in _build
    self._custom_component.set_event_manager(event_manager)
AttributeError: 'SQLExecutorComponent' object has no attribute 'set_event_manager'

### Reproduction

1. Enter in fields for the SQL Executor component (Database URL, query) 
2. Click on the "play" button to run the component 

### Expected behavior

It would run the query with no error messages previously on V1.0.16. The standard "tick" would show on the component to show it running properly. 

### Operating System

macOS Ventura 13.5.1

### Langflow Version

V1.0.19

### Python Version

3.10

### Screenshot

https://prnt.sc/eInlqX0wlqqF, https://prnt.sc/wKBejoiFS4-h

**Comment by tonnyESP** [comment] 2024-10-15 22:16
👋 Same issue here! 

I've tried updating the component code, following the guidelines. No errors are returned, but I still get the message: "Please build the component first" when I "play" the node.

**Comment by Gluepower** [comment] 2024-10-17 06:09
I have this issue with every custom component I have build. 
![image](https://github.com/user-attachments/assets/42bb7b27-abfd-4256-829f-17efeadf0050)

**Comment by joaoguilhermeS** [comment] 2024-10-21 16:35
Hi @SavvySupport, @tonnyESP, @Gluepower, 

Thank you all for your support. This issue will be resolved in the upcoming v1.19.1 release. 

It is a duplicate of Issue #4223 and has been addressed in PR #4230.

**Closed by joaoguilhermeS** 2024-10-21 16:35 UTC
Labels: bug

**Comment by SavvySupport** [comment] 2024-10-30 02:04
Resolved in v1.19.1, or v1.19.post1? 

https://github.com/langflow-ai/langflow/releases

**Comment by dn-scribe** [comment] 2024-12-04 19:14
I have the same problem on v.1.1.1 
After modifying the component I get
"first buid the component"
