### ISSUE TITLE
Issue with saving data to Chroma DB

### ISSUE THREAD

**Issue by sorenaakjaer** [langflow-ai/langflow#2368] opened 2024-06-26 07:13 UTC
**Describe the bug**
When i store data to ChromaDB the folllow issue occours

NotFoundError: Error code: 404 - {'error': {'code': 'DeploymentNotFound',
                             'message': 'The API deployment for this resource does not exist. If you
                             created the deployment within the last 5 minutes, please wait a moment and try
                             again.'}}

[06/26/24 09:06:22] ERROR    2024-06-26 09:06:22 - ERROR    - service - Error stopping tracing service:   service.py:76
                             'NoneType' object has no attribute 'cancel'

**Browser and Version**
 - Browser [Chrome]
 - Version [126.0.6478.115 ]

**To Reproduce**
1. Create project 
2. Import text file from "Directory" component
3. Split text
4. Ad Chroma DB 
5.  Add embedding from Azure OpenAI
6. Test flow

**Screenshots**
![image](https://github.com/langflow-ai/langflow/assets/77328754/8fb90ec9-31df-44d4-bb51-dd1c2cb0ad97)

**Additional context**

**Comment by sorenaakjaer** [comment] 2024-06-26 08:13
I'm getting the same issue if use FAISS vector DB

**Comment by nicoloboschi** [comment] 2024-06-28 09:51
@sorenaakjaer The problem is Azure. The model you're putting must match the exact name of the DEPLOYMENT in azure, can you double check is correct? 

I can correctly use Azure in LangFlow 1.0.5

**Comment by carlosrcoelho** [comment] 2024-07-18 13:24
Hi @sorenaakjaer 
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment] 2024-07-22 17:27
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.

**Closed by carlosrcoelho** 2024-07-22 17:27 UTC
Labels: bug
