### ISSUE TITLE
Conditional routing blocks flow - doesn't behave as expected

### ISSUE THREAD

**Issue by devinbost** [langflow-ai/langflow#3858] opened 2024-09-19 15:13 UTC
### Bug Description

I have a component that's supposed to split data into two flows, but the data is not continuing down the flow. 

### Reproduction

Define a component like the following:

```
# from langflow.field_typing import Data
from langflow.custom import Component
from langflow.io import MessageTextInput, Output
from langflow.schema import Data
from loguru import logger

class CustomComponent(Component):
    display_name = "Query Router"
    description = "Router for sending queries to their appropriate drivers for execution."
    documentation: str = "http://docs.langflow.org/components/custom"
    icon = "custom_components"
    name = "CustomComponent"

    inputs = [
        DataInput(name="instruction_data", display_name="Instruction Data", value='(user_info and deduplicated rows)'),
    ]

    outputs = [
        Output(display_name="Oracle queries", name="oracle_output", method="oracle_output"),
        Output(display_name="Cassandra queries", name="cassandra_output", method="cassandra_output"),
        Output(display_name="Splunk queries", name="splunk_output", method="splunk_output"),
        Output(display_name="MySQL queries", name="mysql_output", method="mysql_output"),
    ]

    
    def oracle_output(self) -> Data:
        input_dict = self.instruction_data
        
        matching_rows = []
        
        for row in input_dict.rows:
            if row["system"] == "oracle":
                matching_rows.append(row)
        
        if len(matching_rows) > 0: 
            
            data = Data(user_id = self.instruction_data.user_id, user_question = self.instruction_data.user_question, rows=matching_rows)
        
            # Set the status to the created Data object
            self.status = data
            
            # Return the Data object
            return data
        else:
            self.stop("oracle_output")
            return None
    
    def cassandra_output(self) -> Data:
        input_dict = self.instruction_data
        
        matching_rows = []
        
        for row in input_dict.rows:
            if row["system"] == "cassandra":
                matching_rows.append(row)
        
        if len(matching_rows) > 0: 
            
            data = Data(user_id = self.instruction_data.user_id, user_question = self.instruction_data.user_question, rows=matching_rows)
        
            # Set the status to the created Data object
            self.status = data
            
            # Return the Data object
            return data
        else:
            self.stop("cassandra_output")
            return None
            
    def splunk_output(self) -> Data:
        input_dict = self.instruction_data
        
        matching_rows = []
        
        for row in input_dict.rows:
            if row["system"] == "splunk":
                matching_rows.append(row)
        
        if len(matching_rows) > 0: 
            
            data = Data(user_id = self.instruction_data.user_id, user_question = self.instruction_data.user_question, rows=matching_rows)
        
            # Set the status to the created Data object
            self.status = data
            
            # Return the Data object
            return data
        else:
            self.stop("splunk_output")
            return None
    
    def mysql_output(self) -> Data:
        input_dict = self.instruction_data
        
        matching_rows = []
        
        for row in input_dict.rows:
            if row["system"] == "mysql":
                matching_rows.append(row)
        
        if len(matching_rows) > 0: 
            
            data = Data(user_id = self.instruction_data.user_id, user_question = self.instruction_data.user_question, rows=matching_rows)
        
            # Set the status to the created Data object
            self.status = data
            
            # Return the Data object
            return data
        else:
            self.stop("mysql_output")
            return None
```

Downstream from it, provide the following components:

```
# from langflow.field_typing import Data
from langflow.custom import Component
from langflow.io import MessageTextInput, Output
from langflow.schema import Data
from loguru import logger

class CustomComponent(Component):
    display_name = "Execute Cassandra queries"
    description = "Execute Cassandra queries"
    documentation: str = "http://docs.langflow.org/components/custom"
    icon = "custom_components"
    name = "CustomComponent"

    inputs = [
        DataInput(name="instruction_data", display_name="Instruction Data", value='(user_info and deduplicated rows)'),
        StrInput(name="DB_ID", display_name="DB_ID", value='Database ID'),
        StrInput(name="DB_TOKEN", display_name="DB_TOKEN", value='Database token'),
    ]

    outputs = [
        Output(display_name="Query output", name="query_output", method="query_output")
    ]

    
    def query_output(self) -> Data:
        print("Running C* execution component")
        import cassio
        from cassandra.query import SimpleStatement
        from cassandra.query import dict_factory
        from typing import List, Dict
        
        namespace = "default_namespace"
        
        cassio.init(
            database_id=self.DB_ID,
            token=self.DB_TOKEN,
            keyspace=namespace
        )
        session = cassio.config.resolve_session()
        
        session.row_factory = dict_factory
        
        from collections import defaultdict
        import json
        from datetime import datetime
        from typing import List
        
        def json_serial(obj):
            """JSON serializer for objects not serializable by default json code"""
            if isinstance(obj, datetime):
                return obj.isoformat()
            raise TypeError ("Type %s not serializable" % type(obj))
        
        if self.instruction_data:
            if self.instruction_data.rows:
                for row in self.instruction_data.rows:
                    query = row["query"]
                    query_output_rows: List[dict] = session.execute(query).all()
                    json_data = json.dumps(query_output_rows, indent=4, default=json_serial)
                    row["data"] = json_data
                
            else:
                print("C* 04 NONE1")
                session.shutdown()
                return None
        else:
            print("C* 04 NONE2")
            session.shutdown()
            return None
            
        print("C* 04 END")
        session.shutdown()
    
        # Set the status to the created Data object
        data = Data(user_id = self.instruction_data.user_id, user_question = self.instruction_data.user_question, rows=self.instruction_data.rows)
        self.status = data
            
        # Return the Data object
        return data
```

and:

```
import mysql.connector
from langflow.custom import Component
from langflow.io import DataInput, StrInput, Output
from langflow.schema import Data
from loguru import logger
import json
from datetime import datetime
from typing import List

print("MYSQL START")

class CustomComponent(Component):
    display_name = "Execute MySQL queries"
    description = "Execute MySQL queries"
    documentation: str = "http://docs.langflow.org/components/custom"
    icon = "custom_components"
    name = "CustomComponent"

    inputs = [
        DataInput(name="instruction_data", display_name="Instruction Data", value='(user_info and deduplicated rows)'),
        StrInput(name="DB_HOST", display_name="DB_HOST", value='Database Host'),
        StrInput(name="DB_USER", display_name="DB_USER", value='Database User'),
        StrInput(name="DB_PASSWORD", display_name="DB_PASSWORD", value='Database Password'),
        StrInput(name="DB_NAME", display_name="DB_NAME", value='Database Name'),
    ]

    outputs = [
        Output(display_name="Query output", name="query_output", method="query_output")
    ]

    def query_output(self) -> Data:
        print("Running mysql execution component")
        from datetime import datetime, date
        def json_serial(obj):
            """JSON serializer for objects not serializable by default json code"""
            if isinstance(obj, (datetime, date)): # This adds support for mysql dates
                return obj.isoformat()
            raise TypeError("Type %s not serializable" % type(obj))

        try:
            # Connect to the MySQL database
            print("MYSQL 01")
            print(self.DB_HOST)
            print(self.DB_USER)
            print(self.DB_PASSWORD)
            print(self.DB_NAME)
            import mysql
            print("MYSQL 011")
            import mysql.connector
            print("MYSQL 012")
            connection = mysql.connector.connect(
                host=self.DB_HOST,
                user=self.DB_USER,
                password=self.DB_PASSWORD,
                database=self.DB_NAME
            )
            print("MYSQL 02")
            cursor = connection.cursor(dictionary=True)
    
            if self.instruction_data:
                if self.instruction_data.rows:
                    for row in self.instruction_data.rows:
                        query = row["query"]
                        print("MYSQL 03")
                        cursor.execute(query)
                        query_output_rows = cursor.fetchall()
                        json_data = json.dumps(query_output_rows, indent=4, default=json_serial)
                        row["data"] = json_data
                else:
                    print("MYSQL 04 NONE1")
                    cursor.close()
                    connection.close()
                    return None
            else:
                print("MYSQL 04 NONE2")
                cursor.close()
                connection.close()
                return None
    
            # Close the cursor and connection
            print("MYSQL 04")
            cursor.close()
            connection.close()

        except mysql.connector.Error as err:
            logger.error(f"Error: {err}")
            return None

        # Set the status to the created Data object
        data = Data(user_id=self.instruction_data.user_id, user_question=self.instruction_data.user_question, rows=self.instruction_data.rows)
        self.status = data

        return data
```

After these, provide the final component:
```
# from langflow.field_typing import Data
from langflow.custom import Component
from langflow.io import MessageTextInput, Output
from langflow.schema import Data

class CustomComponent(Component):
    display_name = "Custom Component"
    description = "Use as a template to create your own component."
    documentation: str = "http://docs.langflow.org/components/custom"
    icon = "custom_components"
    name = "CustomComponent"

    inputs = [
        #DataInput(name="splunk_rows", display_name="Splunk rows", value="Hello, World!"),
        DataInput(name="cassandra_rows", display_name="Cassandra rows", value="(insert rows)"),
        DataInput(name="oracle_rows", display_name="Oracle rows", value="(insert rows)"),
        DataInput(name="mysql_rows", display_name="MySQL rows", value="(insert rows)"),
    ]

    outputs = [
        Output(display_name="Output", name="output", method="build_output"),
    ]

    def build_output(self) -> Data:
        print("Running query result combiner component")
        all_rows = [] 
        print(self.cassandra_rows.rows)
        print(type(self.cassandra_rows.rows))
        for row in self.cassandra_rows.rows:
            print(f"row is: {row}")
            row_obj = {"instruction": row["instruction"], "data": row["data"]}
            all_rows.append(row_obj)
        
        for row in self.mysql_rows.rows:
            row_obj = {"instruction": row["instruction"], "data": row["data"]}
            all_rows.append(row_obj)
            
        user_id = self.cassandra_rows.user_id
        user_question = self.cassandra_rows.user_question
        
        data = Data(user_id=user_id, user_question = user_question, rows = all_rows)
        self.status = data
        return data

```

Pass a data object with the following properties into the flow on the left:
```
user_id (int)
user_question (string)
rows, defined like in the example below:

[{"system":"cassandra","query":"SELECT * FROM default_namespace.base_data WHERE int_id = 8888888888","instruction":["check TIER_STATUS_CHG_DT, which is the date","Check if SPL_CUS_TYPE = C. If so, then the user did classify, which means they can't redeem or utilize their miles.","check CUR_BAL. That's the balance in miles."]},{"system":"cassandra","query":"SELECT * FROM default_namespace.login_data WHERE cus_id = 8888888888","instruction":["Check the LATEST_LOGIN_ON date and provide that to answer this question."]}]
```

Connect it in a flow like the following:

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/84fbefec-bb10-48d4-a438-bbd570eee35d">

Execution does not reach the Custom Component on the right. It just mysteriously stops executing. 

### Expected behavior

The Cassandra queries should be executed by the top component, and the MySQL queries should be executed by the bottom component. Then, the results should be combined in the final component. 
In this exact reproduction case, since no mysql queries exist, only the Cassandra flow should execute, and the final component should use only the results of the Cassandra component since no other results exist to combine. 

### Operating System

Mac M1 (Apple Silicon)

### Langflow Version

1.0.18

### Python Version

3.10

### Flow File

Initialize the data by running these components in this flow:
<img width="725" alt="image" src="https://github.com/user-attachments/assets/775c0c56-bea9-4493-b374-03b38be02e61">
[SIA_v4_init.json](https://github.com/user-attachments/files/17061775/SIA_v4_init.json)

Then, use this flow to reproduce the issue:
[SIA_v4 non-async.json](https://github.com/user-attachments/files/17061748/SIA_v4.non-async.json)

**Comment by devinbost** [comment] 2024-09-19 15:30
That's actually quite useful for a bot response. I'll try that and report if it solves the problem.

**Comment by edwinjosechittilappilly** [comment] 2024-09-24 18:18
Hi @devinbost,

I hope you were able to resolve the issue with the feedback provided. To assist you further, I’ve attached a sample of a multi-case router component that might be helpful:

```python
from langflow.custom import Component
from langflow.io import BoolInput, DropdownInput, MessageInput, MessageTextInput, Output
from langflow.schema.message import Message


class MultiConditionalRouterComponent(Component):
    display_name = "Multi Conditional Router"
    description = "Routes an input message to a corresponding output based on text comparison."
    icon = "equal"
    name = "ConditionalRouter"

    inputs = [
        MessageTextInput(
            name="input_text",
            display_name="Input Text",
            info="The primary text input for the operation.",
        ),
        DropdownInput(
            name="operator",
            display_name="Operator",
            options=["equals", "not equals", "contains", "starts with", "ends with"],
            info="The operator to apply for comparing the texts.",
            value="equals",
            advanced=True,
        ),
        MessageTextInput(
            name="case_1_text",
            display_name="Case 1 Text",
            info="The text input for Case 1 comparison.",
        ),
        MessageTextInput(
            name="case_2_text",
            display_name="Case 2 Text",
            info="The text input for Case 2 comparison.",
        ),
        MessageTextInput(
            name="case_3_text",
            display_name="Case 3 Text",
            info="The text input for Case 3 comparison.",
        ),
        BoolInput(
            name="case_sensitive",
            display_name="Case Sensitive",
            info="If true, the comparison will be case sensitive.",
            value=False,
            advanced=True,
        ),
        MessageInput(
            name="message",
            display_name="Message",
            info="The message to pass through either route.",
        ),
    ]

    outputs = [
        Output(display_name="Case 1 Response", name="case_1_result", method="case_1_response"),
        Output(display_name="Case 2 Response", name="case_2_result", method="case_2_response"),
        Output(display_name="Case 3 Response", name="case_3_result", method="case_3_response"),
        Output(display_name="Default Response", name="default_result", method="default_response"),
    ]

    def evaluate_condition(self, input_text: str, match_text: str, operator: str, case_sensitive: bool) -> bool:
        if not case_sensitive:
            input_text = input_text.lower()
            match_text = match_text.lower()

        conditions = {
            "equals": input_text == match_text,
            "not equals": input_text != match_text,
            "contains": match_text in input_text,
            "starts with": input_text.startswith(match_text),
            "ends with": input_text.endswith(match_text),
        }
        return conditions.get(operator, False)

    def case_response(self, case_text: str, case_name: str) -> Message:
        result = self.evaluate_condition(self.input_text, case_text, self.operator, self.case_sensitive)
        if result:
            self.status = self.message
            return self.message
        else:
            self.stop(case_name)
            return None  # type: ignore

    def case_1_response(self) -> Message:
        return self.case_response(self.case_1_text, "case_1_result")

    def case_2_response(self) -> Message:
        return self.case_response(self.case_2_text, "case_2_result")

    def case_3_response(self) -> Message:
        return self.case_response(self.case_3_text, "case_3_result")

    def case_4_response(self) -> Message:
        # Logic for case 4 can be added here if needed
        self.stop("case_4_result")
        return None  # type: ignore

    def default_response(self) -> Message:
        # Check if all cases are false
        case_1_result = self.evaluate_condition(self.input_text, self.case_1_text, self.operator, self.case_sensitive)
        case_2_result = self.evaluate_condition(self.input_text, self.case_2_text, self.operator, self.case_sensitive)
        case_3_result = self.evaluate_condition(self.input_text, self.case_3_text, self.operator, self.case_sensitive)
        if not (case_1_result or case_2_result or case_3_result):
            self.status = self.message
            return self.message
        else:
            self.stop("default_result")
            return None  # type: ignore
        return None

```

If you have any more questions or encounter further issues, please feel free to reach out. I’ll be closing the issue for now, but don’t hesitate to reopen it if needed.

**Comment by edwinjosechittilappilly** [comment] 2024-09-24 18:21
Also Attaching a Sample flow
[Multi Conditional Router Testing.json](https://github.com/user-attachments/files/17119223/Multi.Conditional.Router.Testing.json)
<img width="1018" alt="Screenshot 2024-09-24 at 2 20 28 PM" src="https://github.com/user-attachments/assets/d3e17030-a60f-45d3-8710-8c1babe0144f">

**Comment by edwinjosechittilappilly** [comment] 2024-09-25 14:30
I hope the issue is resolved. I am currently closing the issue, but please feel free to reopen it if any further problems arise.

Thank you!

**Closed by edwinjosechittilappilly** 2024-09-25 14:30 UTC
Labels: bug
