### ISSUE TITLE
in 1.0.14 URGENT : Langflow Front end times out while saving, deletes current workflow

### ISSUE THREAD

**Issue by Arron-Clague** [langflow-ai/langflow#3164] opened 2024-08-02 12:49 UTC
### Bug Description

When the front times out, for example with a save or cancel save, the current workflow is show no components. Logging off and logging in again deletes the flow entirely ! 

### Reproduction

Duplicate an  existing flow for safety. 
Open the flow 
Allow the front end to timeout or save to fail
restart
navigate back to collectoion
navigate to flow : flow is empty
navigate back to collection
Flow is now deleted

### Expected behavior

To save correctly and not delete user flows.

### Who can help?

@ogabrielluiz
@nicoloboschi
@zzzming
@jordanrfrazier
@mfortman11
@NadirJ

### Operating System

Ubuntu 22.04

### Langflow Version

1.0.14

### Python Version

3.10

**Comment by Cristhianzl** [comment] 2024-08-02 14:28
hi @Arron-Clague 
I couldn't reproduce this error.
Could you please provide a detailed step by step or a video to us?
Thank you!

**Comment by Arron-Clague** [comment] 2024-08-05 07:50
Hi : I think its a DB migration error : 2024-08-05 08:47:54 - ERROR    - service - Error migrating transactions  service.py:221
                             from monitor service to database: (sqlite3.IntegrityError) NOT NULL
                             constraint failed: transaction.flow_id
                             [SQL: INSERT INTO "transaction" (timestamp, vertex_id, target_id,
                             inputs, outputs, status, error, flow_id, id) VALUES (?, ?, ?, ?, ?, ?,
                             ?, ?, ?)]
                             [parameters: [('2024-07-29 11:53:22.000000', 'ChatInput-y0ZNG', None,
                             '{"files": [], "code": "from langflow.base.data.utils import
                             IMG_FILE_TYPES, TEXT_FILE_TYPES\\nfrom langflow.base.io.chat import
                             ChatComponent\\nfrom  ... (2625 characters truncated) ... = message\\n
                             return message\\n", "input_value": "hi", "sender": "User",
                             "sender_name": "User", "session_id": "", "should_store_message": true}',
                             '{"results": {"message": {"text_key": "text", "data": {"text": "hi",
                             "sender": "User", "sender_name": "User", "session_id": "", "files": [],
                             "timestam ... (668 characters truncated) ... sage"}], "timedelta": null,
                             "duration": null, "component_display_name": "Chat Input",
                             "component_id": "ChatInput-y0ZNG", "used_frozen_result": false}',
                             'success', None, None, '5a5544bfb2574a7ab9859956bbe3d267'), ('2024-07-29
                             11:53:23.000000', 'ChatInput-y0ZNG', 'OpenAIModel-VJs7s', '{"files": [],
                             "code": "from langflow.base.data.utils import IMG_FILE_TYPES,
                             TEXT_FILE_TYPES\\nfrom langflow.base.io.chat import ChatComponent\\nfrom
                             ... (2625 characters truncated) ... = message\\n        return
                             message\\n", "input_value": "hi", "sender": "User", "sender_name":
                             "User", "session_id": "", "should_store_message": true}', '{"results":
                             {"message": {"text_key": "text", "data": {"text": "hi", "sender":
                             "User", "sender_name": "User", "session_id": "", "files": [], "timestam
                             ... (668 characters truncated) ... sage"}], "timedelta": null,
                             "duration": null, "component_display_name": "Chat Input",
                             "component_id": "ChatInput-y0ZNG", "used_frozen_result": false}',
                             'success', None, None, '9c74fa2f18064e2b9766047dcd53ae63'), ('2024-07-29
                             11:53:24.000000', 'OpenAIModel-VJs7s', None, '{"code": "import
                             operator\\nfrom functools import reduce\\n\\nfrom langchain_openai
                             import ChatOpenAI\\nfrom pydantic.v1 import SecretStr\\n\\nfrom l ...
                             (4688 characters truncated) ... ": "http://10.0.0.205:8999/v1",
                             "openai_api_key": "11111", "output_schema": {}, "seed": 1, "stream":
                             false, "system_message": "", "temperature": 0.1}', '{"results": {},
                             "artifacts": {"text_output": {"repr": "Hi! It\'s nice to meet you. Is
                             there something I can help you with or would you like to chat?" ... (374
                             characters truncated) ...  "timedelta": null, "duration": null,
                             "component_display_name": "KONI Connect (1)", "component_id":
                             "OpenAIModel-VJs7s", "used_frozen_result": false}', 'success', None,
                             None, '3da001bd27b544a6b57ed44ffc44c69f'), ('2024-07-29
                             11:53:24.000000', 'OpenAIModel-VJs7s', 'ChatOutput-6hfYp', '{"code":
                             "import operator\\nfrom functools import reduce\\n\\nfrom
                             langchain_openai import ChatOpenAI\\nfrom pydantic.v1 import
                             SecretStr\\n\\nfrom l ... (4688 characters truncated) ... ":
                             "http://10.0.0.205:8999/v1", "openai_api_key": "11111", "output_schema":
                             {}, "seed": 1, "stream": false, "system_message": "", "temperature":
                             0.1}', '{"results": {}, "artifacts": {"text_output": {"repr": "Hi! It\'s
                             nice to meet you. Is there something I can help you with or would you
                             like to chat?" ... (374 characters truncated) ...  "timedelta": null,
                             "duration": null, "component_display_name": "KONI Connect (1)",
                             "component_id": "OpenAIModel-VJs7s", "used_frozen_result": false}',
                             'success', None, None, '2f12bba3b25149ce9b699e8cbece1b85'), ('2024-07-29
                             11:53:24.000000', 'ChatOutput-6hfYp', None, '{"input_value": "Hi! It\'s
                             nice to meet you. Is there something I can help you with or would you
                             like to chat?", "code": "from langflow.base.io.chat  ... (2562
                             characters truncated) ... ge\\n        return message\\n",
                             "data_template": "{text}", "sender": "Machine", "sender_name": "AI",
                             "session_id": "", "should_store_message": true}', '{"results":
                             {"message": {"text_key": "text", "data": {"text": "Hi! It\'s nice to
                             meet you. Is there something I can help you with or would you like t ...
                             (1131 characters truncated) ... ge"}], "timedelta": null, "duration":
                             null, "component_display_name": "Chat Output", "component_id":
                             "ChatOutput-6hfYp", "used_frozen_result": false}', 'success', None,
                             None, 'a898ee76f9864a25a9480ac9bd573dbd')]]
                             (Background on this error at: https://sqlalche.me/e/20/gkpj)

**Comment by Arron-Clague** [comment] 2024-08-05 09:00
so : ive backed up my flows via Export all : stopped Langflow, and deleted langflow.db and, re- run create superuser, and still the DB is giving errors : it is still getting corrupt data from somewhere : looks like it from outdated custom components : langflow superuser
Username: arroncx
Password:
[08/05/24 09:55:49] ERROR    2024-08-05 09:55:49 - ERROR    - service - Error migrating transactions  service.py:221
                             from monitor service to database: (sqlite3.IntegrityError) NOT NULL
                             constraint failed: transaction.flow_id
                             [SQL: INSERT INTO "transaction" (timestamp, vertex_id, target_id,
                             inputs, outputs, status, error, flow_id, id) VALUES (?, ?, ?, ?, ?, ?,
                             ?, ?, ?)]
                             [parameters: [('2024-07-29 11:53:22.000000', 'ChatInput-y0ZNG', None,
                             '{"files": [], "code": "from langflow.base.data.utils import
                             IMG_FILE_TYPES, TEXT_FILE_TYPES\\nfrom langflow.base.io.chat import
                             ChatComponent\\nfrom  ... (2625 characters truncated) ... = message\\n
                             return message\\n", "input_value": "hi", "sender": "User",
                             "sender_name": "User", "session_id": "", "should_store_message": true}',
                             '{"results": {"message": {"text_key": "text", "data": {"text": "hi",
                             "sender": "User", "sender_name": "User", "session_id": "", "files": [],
                             "timestam ... (668 characters truncated) ... sage"}], "timedelta": null,
                             "duration": null, "component_display_name": "Chat Input",
                             "component_id": "ChatInput-y0ZNG", "used_frozen_result": false}',
                             'success', None, None, 'f5c330f595db42c2894f04c775f21582'), ('2024-07-29
                             11:53:23.000000', 'ChatInput-y0ZNG', 'OpenAIModel-VJs7s', '{"files": [],
                             "code": "from langflow.base.data.utils import IMG_FILE_TYPES,
                             TEXT_FILE_TYPES\\nfrom langflow.base.io.chat import ChatComponent\\nfrom
                             ... (2625 characters truncated) ... = message\\n        return
                             message\\n", "input_value": "hi", "sender": "User", "sender_name":
                             "User", "session_id": "", "should_store_message": true}', '{"results":
                             {"message": {"text_key": "text", "data": {"text": "hi", "sender":
                             "User", "sender_name": "User", "session_id": "", "files": [], "timestam
                             ... (668 characters truncated) ... sage"}], "timedelta": null,
                             "duration": null, "component_display_name": "Chat Input",
                             "component_id": "ChatInput-y0ZNG", "used_frozen_result": false}',
                             'success', None, None, 'ad0415c103df4e2da45c493547ddad12'), ('2024-07-29
                             11:53:24.000000', 'OpenAIModel-VJs7s', None, '{"code": "import
                             operator\\nfrom functools import reduce\\n\\nfrom langchain_openai
                             import ChatOpenAI\\nfrom pydantic.v1 import SecretStr\\n\\nfrom l ...
                             (4688 characters truncated) ... ": "http://10.0.0.205:8999/v1",
                             "openai_api_key": "11111", "output_schema": {}, "seed": 1, "stream":
                             false, "system_message": "", "temperature": 0.1}', '{"results": {},
                             "artifacts": {"text_output": {"repr": "Hi! It\'s nice to meet you. Is
                             there something I can help you with or would you like to chat?" ... (374
                             characters truncated) ...  "timedelta": null, "duration": null,
                             "component_display_name": "KONI Connect (1)", "component_id":
                             "OpenAIModel-VJs7s", "used_frozen_result": false}', 'success', None,
                             None, '86d96c71b64a4ef3adc31e24cff95ef5'), ('2024-07-29
                             11:53:24.000000', 'OpenAIModel-VJs7s', 'ChatOutput-6hfYp', '{"code":
                             "import operator\\nfrom functools import reduce\\n\\nfrom
                             langchain_openai import ChatOpenAI\\nfrom pydantic.v1 import
                             SecretStr\\n\\nfrom l ... (4688 characters truncated) ... ":
                             "http://10.0.0.205:8999/v1", "openai_api_key": "11111", "output_schema":
                             {}, "seed": 1, "stream": false, "system_message": "", "temperature":
                             0.1}', '{"results": {}, "artifacts": {"text_output": {"repr": "Hi! It\'s
                             nice to meet you. Is there something I can help you with or would you
                             like to chat?" ... (374 characters truncated) ...  "timedelta": null,
                             "duration": null, "component_display_name": "KONI Connect (1)",
                             "component_id": "OpenAIModel-VJs7s", "used_frozen_result": false}',
                             'success', None, None, '39e92a1f25804080a5e08807f18da149'), ('2024-07-29
                             11:53:24.000000', 'ChatOutput-6hfYp', None, '{"input_value": "Hi! It\'s
                             nice to meet you. Is there something I can help you with or would you
                             like to chat?", "code": "from langflow.base.io.chat  ... (2562
                             characters truncated) ... ge\\n        return message\\n",
                             "data_template": "{text}", "sender": "Machine", "sender_name": "AI",
                             "session_id": "", "should_store_message": true}', '{"results":
                             {"message": {"text_key": "text", "data": {"text": "Hi! It\'s nice to
                             meet you. Is there something I can help you with or would you like t ...
                             (1131 characters truncated) ... ge"}], "timedelta": null, "duration":
                             null, "component_display_name": "Chat Output", "component_id":
                             "ChatOutput-6hfYp", "used_frozen_result": false}', 'success', None,
                             None, '777b56bea08e431f8fc895dc8a9e420b')]]
                             (Background on this error at: https://sqlalche.me/e/20/gkpj)
Default folder created successfully.
Superuser created successfully.

**Comment by Arron-Clague** [comment] 2024-08-06 14:04
@appks : Its not a complete solution, but while this gets resolved, backing up the flows via export, deleting langflow.db, and restarting with a new superuser account did get me back running again after re-importing the flows. There are still errors in the DB (as above) but I haven't lost any flows, and the load time issue has gone.

**Comment by appoks** [comment] 2024-08-07 21:48
I think this was solved for the version on 'main'

Here's how I could reproduce this bug on my 1.0.14 version (dockerized install)

https://github.com/user-attachments/assets/96215386-00a3-4078-b2e0-9662f1bf9b9d

However, I noticed that the there's a new loading on the version I cloned today, directly from main.

![image](https://github.com/user-attachments/assets/3129ddb9-f466-415d-b4c2-6ee59315a93e)

Not sure if it's really fixed now, but it seems worth to share;

**Comment by appoks** [comment] 2024-08-07 21:50
The issue happens mostly with the flows that has the load time issue as Arron said. I've tried to make it break with other flows that load more fast and could not break any of them. If the flow takes some secs to load, messing the canvas around will delete the flow.

**Comment by lucaseduoli** [comment] 2024-08-13 19:42
Fixed in the last version! Feel free to test it and open this issue if you find anything wrong!

Thanks for the feedback.

**Closed by lucaseduoli** 2024-08-13 19:42 UTC
Labels: bug
