### ISSUE TITLE
Chroma DB build Error

### ISSUE THREAD

**Issue by corsair01** [langflow-ai/langflow#2369] opened 2024-06-26 08:17 UTC
**Describe the bug**
When I build chroma db, this error occoured.

**Browser and Version**
 - Browser [chrome]
 - Version [126.0.6478.127]

**To Reproduce**
1. Create data
2. Add Chroma db
3. Add openAI embedding
4. Build flow

**Screenshots**
![image](https://github.com/langflow-ai/langflow/assets/141121545/af62eacb-d7ae-4c4e-af58-d5532b1cdc5b)
![image](https://github.com/langflow-ai/langflow/assets/141121545/2f4d1ebd-8772-40f8-aa7e-e158ad2490d9)

**Additional context**

**Comment by corsair01** [comment] 2024-06-26 08:19
![image](https://github.com/langflow-ai/langflow/assets/141121545/1add242b-0946-4c06-b3c0-8add78d76ceb)

I uploaded the wrong first screenshot. The correct screenshot is this.

**Comment by nicoloboschi** [comment] 2024-06-28 09:49
hey @corsair01 do you have the entire error from the logs? that could be helpful.
By the way, using version 1.0.5, I can't reproduce the error

**Comment by carlosrcoelho** [comment] 2024-07-18 13:25
Hi @corsair01 
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment] 2024-07-22 17:46
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.

Please try out the new version 1.0.11.

<img width="957" alt="image" src="https://github.com/user-attachments/assets/6024798c-7a23-4112-813e-c23f5580d537">

**Closed by carlosrcoelho** 2024-07-22 17:46 UTC
Labels: bug
