### ISSUE TITLE
switched enviro and back - relaunch langflow - can see flows - but when clciking - get 'Sorry, we found an unexpected error!  Please report errors with detailed tracebacks on the GitHub Issues page. Thank you!

### ISSUE THREAD

**Issue by davelegion** [langflow-ai/langflow#4080] opened 2024-10-09 13:43 UTC
Im unsure how I can access these again at the current time..

**Comment by greenmotion** [comment] 2024-10-09 15:52
Not sure if this helps, but I've been suffering some of these errors as well, without even changing environments. One day the flows work, the next day - without any changes - the flows fail. I don't know if this is caused by corrupted or what.

What I found out is that if you go to the All page, select the flow and "duplicate" it, the new duplicated flow opens and works correctly. Then delete the old flow.  Unfortunately I've had to do that a few times already and I have no idea why these flows keep "corrupting" if that is indeed what is happening. No stack traces in the logs when this happens.

**Comment by davelegion** [comment] 2024-10-09 17:17
appreciate the insight. There was a mismatch in the schema and where new flows were created. 

I tried upgrading to 1.0.18 but there were no flows in the langflow portal anymore. There seem to be a ticket addressing this already with a fix in 1.0.19 so will wait for that before i touch anything else.

Just need to hack our ways out for the issues for now., which is understandable given its still in its infancy.

**Comment by edwinjosechittilappilly** [comment] 2024-11-25 19:33
Hi @vertgo ,
Can you check if the issue persists in the latest version of langflow version 1.1.1  ?

Happy to help if the issue still occurs.

**Comment by edwinjosechittilappilly** [comment] 2024-11-27 15:12
We are currently closing this issue. If you encounter any further problems, please reopen the issue and let us know. We are happy to help.

**Closed by edwinjosechittilappilly** 2024-11-27 15:12 UTC
Labels: bug
